import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex items-center justify-center w-full h-screen flex flex-row">
          <div className=" w-70 h-120 m-20 rounded-lg bg-[#151515]">
            <div className="flex items-center justify-center w-full h-1/6 bg-[#0ab6ab] rounded-lg ">
              <h1 className="text-white text-[20px] font-bold">
                Todo App
              </h1>
            </div>
            <div className=" h-5/6 flex mt-10 flex-col gap-4">{children}</div>
        
        </div>
      </body>
    </html>
  );
}
